Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Use a private network so that we don't have to worry about forwarding ports
  config.vm.network "private_network", ip: "192.168.50.11"
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Enable ssh forward agent
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |v|
    v.name = "FreeItLessons"
    v.memory = 1024

    # Only allow drift of 1 sec, instead of 20 min default
    v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end

  # Bootstrap script for configuring VM
  config.vm.provision :shell, path: "bootstrap.sh"

  #config.vm.synced_folder "vagrant/", "/home/ubuntu/vagrant", create: true
  #config.vm.synced_folder ".", "/home/vagrant/FreeItLessons", owner: "vagrant", group: "vagrant"

end

