version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run: python --version
      - run: pip3 install -r requirements.txt
      - run: pip3 install -r requirements.dev.txt
      - run: pytest tests

workflows:
  sample:
    jobs:
      - tests

