version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run:
          command: |
            pyenv virtualenv 3.9.7 venv
            pyenv shell venv
            pip3 install -r requirements.txt
            pip3 install -r requirements.dev.txt
            pytest tests

workflows:
  ci:
    jobs:
      - tests
