name: CI (linter + unit tests check)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install -r requirements.dev.txt
      - name: Lint with flake8
        run: |
          flake8 --extend-ignore=E501,E800 FreeItLessons/
      - name: Test with unittest
        run: |
          pip3 install ddt
          python3 manage.py test tests
